#!/bin/bash

#source ./env.sh

BUILD_VIDEO=0
BUILD_X264=0
#Lin BUILD_AMRNB=full # 0, light or full
BUILD_AMRNB=0
BUILD_AMRWB=0
BUILD_GPLV3_ZRTP=0
#build srtp
BUILD_SRTP=1
BUILD_SILK=0
BUILD_G729=1
BUILD_TUNNEL=0
BUILD_WEBRTC_AECM=1
BUILD_FOR_X86=0
USE_JAVAH=0

NDK_BUILD=`which ndk-build`
NUMCPUS=`grep -c '^processor' /proc/cpuinfo`

if [ -z "$NDK_BUILD" ]
then
    echo "NDK not installed, please install Android NDK!"
    exit
fi

if [ -z "$NUMCPUS" ]
then
    echo "NUMCPUS is not defined, use default 4"
    NUMCPUS=4
fi


export TOPDIR=`pwd`

echo "TOPDIR=$TOPDIR"

#first prepare source
#source ./prepare_sources.sh

BUILD_CMD="$NDK_BUILD BUILD_VIDEO=$BUILD_VIDEO BUILD_X264=$BUILD_X264 BUILD_AMRNB=$BUILD_AMRNB BUILD_AMRWB=$BUILD_AMRWB BUILD_GPLV3_ZRTP=$BUILD_GPLV3_ZRTP BUILD_SILK=$BUILD_SILK BUILD_G729=$BUILD_G729 BUILD_GPLV3_ZRTP=$BUILD_GPLV3_ZRTP BUILD_SRTP=$BUILD_SRTP BUILD_TUNNEL=$BUILD_TUNNEL BUILD_WEBRTC_AECM=$BUILD_WEBRTC_AECM BUILD_FOR_X86=$BUILD_FOR_X86 USE_JAVAH=$USE_JAVAH -j$NUMCPUS"

echo BUILD_CMD=$BUILD_CMD

$BUILD_CMD
